## 5) 다중 입력에 대한 실습

이번에는 독립 변수 $x$가 2개 이상인 선형 회귀와 로지스틱 회귀에 대해서 배워보도록 하겠다. 비용 함수와 옵티마이저 등을 사용하는 원리는 동일하다.

### 1.다중 선형 회귀

딥러닝 챕터로 들어가게되면 대부분의 입력들은 독립 변수가 2개 이상이다. 이는 모델을 직접 코딩하는 관점에서는 입력 벡터의 차원이 2 이상이라고 할 수 있다. $y$를 결정하는데 있어 독립 변수가 3개인 선형 회귀를 풀어보자. 중간 고사, 기말 고사, 그리고 추가 점수를 어떤 공식을 통해 최종 점수를 계산한 데이터가 있다.

|Midterm($x_1$)	|Final($x_2$)	|Added point($x_3$)	|Score(1000달러)(y)
|--|--|--|--
|70	|85	|11	|73
|71	|89	|18	|82
|50	|80	|20	|72
|99	|20	|10	|57
|50	|10	|10	|34
|20	|99	|10	|58
|40	|50	|20	|56

이 경우 가설은 다음과 같다.

$H(X) = {W_1x_1 + W_2x_2 + W_3x_3 + b}$

위의 데이터 중 상위 5개의 데이터만 훈련에 사용하고, 나머지 2개는 테스트에 사용해보겠다.

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential # 케라스의 Sequential()을 임포트
from tensorflow.keras.layers import Dense # 케라스의 Dense()를 임포트
from tensorflow.keras import optimizers # 케라스의 옵티마이저를 임포트

In [2]:
X=np.array([[70, 85, 11],
            [71, 89, 18],
            [50, 80, 20],
            [99, 20, 10],
            [50, 10, 10]]) # 중간, 기말, 가산점
# 입력 벡터의 차원은 3이다. 즉, input_dim은 3이다.

y = np.array([73, 82, 72, 57, 34]) # 최종 성적
# 출력 벡터의 차원은 1이다. 즉, output_dim은 1이다.

In [3]:
model = Sequential()
model.add(Dense(1, input_dim = 3, activation = 'linear'))
model

In [5]:
sgd = optimizers.SGD(lr = 0.00001) 
sgd # 학습률(learning rate, lr)은 0.00001로 한다.

In [6]:
model.compile(optimizer = sgd,
              loss = 'mse',
              metrics = ['mse'])
# sgd는 경사 하강법을 의미.
# 손실 함수(Loss function)은 평균제곱오차 mse를 사용한다.

In [7]:
model.fit(X, y, batch_size = 1, epochs = 2000, shuffle = False)
# 주어진 X와 y 데이터에 대해서 오차를 최소화하는 작업을 2,000번 시도한다.

Epoch 1/2000
5/5 [==============================] - 0s 1ms/step - loss: 3626.5435 - mse: 3626.5435
Epoch 2/2000
5/5 [==============================] - 0s 1ms/step - loss: 500.0698 - mse: 500.0698
Epoch 3/2000
5/5 [==============================] - 0s 1ms/step - loss: 69.2232 - mse: 69.2232
Epoch 4/2000
5/5 [==============================] - 0s 1ms/step - loss: 12.1799 - mse: 12.1799
Epoch 5/2000
5/5 [==============================] - 0s 1ms/step - loss: 5.4848 - mse: 5.4848
Epoch 6/2000
5/5 [==============================] - 0s 1ms/step - loss: 5.0145 - mse: 5.0145
Epoch 7/2000
5/5 [==============================] - 0s 1ms/step - loss: 5.1006 - mse: 5.1006
Epoch 8/2000
5/5 [==============================] - 0s 1ms/step - loss: 5.1481 - mse: 5.1481
Epoch 9/2000
5/5 [==============================] - 0s 2ms/step - loss: 5.1486 - mse: 5.1486
Epoch 10/2000
5/5 [==============================] - 0s 1ms/step - loss: 5.1286 - mse: 5.1286
Epoch 11/2000
5/5 [==============================] - 0s

앞서 실습한 선형 회귀 코드와 거의 동일한데 달라진 점은 입력의 차원이 3으로 바뀌면서, input_dim의 인자값이 3으로 바뀌었다는 점이다. 이는 입력 벡터의 차원이 3임을 의미한다.

아직 오차(loss)가 줄어들 여지가 있지만, 여기서는 이 정도에서 예측 작업을 해보겠다.

In [8]:
print(model.predict(X))

[[73.003395]
 [81.971   ]
 [72.02425 ]
 [57.13865 ]
 [33.747944]]


기존 데이터를 주고 예측을 시켰을 때 아직 정확하게 예측하는 건 아니지만 어느정도 실제값에 근접한 예측을 하는 것을 볼 수 있다. 이제 훈련할 때 사용하지 않았던 데이터를 가지고 예측 작업을 수행해보겠다.

In [10]:
X_test = np.array([[20, 99, 10],
                   [40, 50, 20]]) # 각각 58점과 56점을 예측해야 한다.
print(model.predict(X_test))

[[57.942245]
 [55.92994 ]]


### 2.다중 로지스틱 회귀

$y$를 결정하는데 있어 독립 변수 $x$가 2개인 로지스틱 회귀를 풀어보자. 꽃받침(Sepal)의 길이와 꽃잎(Petal)의 길이와 해당 꽃이 A인지 B인지가 적혀져 있는 데이터가 있을 때, 새로 조사한 꽃받침의 길이와 꽃잎의 길이로부터 무슨 꽃인지 예측할 수 있는 모델을 만들고자 한다면 이 때 독립 변수 $x$는 2개가 된다.

|SepalLengthCm($x_1$)	|PetalLengthCm($x_2$)	|Species(y)
|--|--|--
|5.1	|3.5	|A
|4.7	|3.2	|A
|5.2	|1.8	|B
|7	|4.1	|A
|5.1	|2.1	|B

이 경우 가설은 다음과 같다.

$H(X) = sigmoid({W_1x_1 + W_2x_2 + b})$

이제 독립 변수가 2개인 좀 더 간단한 예를 들고, 이를 케라스로 구현해보자. OR 게이트는 0 또는 1의 값을 입력으로 받는데, 두 개의 입력 $x_1$, $x_2$ 중 하나라도 1이면 출력값 $y$가 1이 되고 두 개의 입력이 모두 0인 경우에만 출력값이 0이 되는 게이트이다. 로지스틱 회귀를 통해 OR 게이트를 구현해보자.

In [11]:
import numpy as np
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]]) # 입력 벡터의 차원은 2이다. 즉, input_dim은 2이다.
y = np.array([0, 1, 1, 1]) # 출력 벡터의 차원은 1이다. 즉, output_dim은 1이다.


In [12]:
from tensorflow.keras.models import Sequential # 케라스의 Sequential()을 임포트
from tensorflow.keras.layers import Dense # 케라스의 Dense()를 임포트
from tensorflow.keras import optimizers # 케라스의 옵티마이저를 임포트

In [13]:
model = Sequential()
model.add(Dense(1, input_dim = 2, activation = 'sigmoid')) # 이제 입력의 차원은 2이다.

In [15]:
model.compile(optimizer = 'sgd',
              loss = 'binary_crossentropy',
              metrics = ['binary_accuracy'])
# sgd는 경사 하강법을 의미.
# 손실 함수(Loss function)는 binary_crossentropy(이진 크로스 엔트로피)를 사용한다.

In [16]:
model.fit(X, y, batch_size = 1, epochs = 800, shuffle = False)

Epoch 1/800
4/4 [==============================] - 0s 1ms/step - loss: 0.3655 - binary_accuracy: 1.0000
Epoch 2/800
4/4 [==============================] - 0s 3ms/step - loss: 0.3646 - binary_accuracy: 0.7500
Epoch 3/800
4/4 [==============================] - 0s 2ms/step - loss: 0.3638 - binary_accuracy: 0.7500
Epoch 4/800
4/4 [==============================] - 0s 2ms/step - loss: 0.3630 - binary_accuracy: 0.7500
Epoch 5/800
4/4 [==============================] - 0s 1ms/step - loss: 0.3621 - binary_accuracy: 0.7500
Epoch 6/800
4/4 [==============================] - 0s 2ms/step - loss: 0.3613 - binary_accuracy: 0.7500
Epoch 7/800
4/4 [==============================] - 0s 2ms/step - loss: 0.3606 - binary_accuracy: 0.7500
Epoch 8/800
4/4 [==============================] - 0s 2ms/step - loss: 0.3598 - binary_accuracy: 0.7500
Epoch 9/800
4/4 [==============================] - 0s 2ms/step - loss: 0.3590 - binary_accuracy: 0.7500
Epoch 10/800
4/4 [==============================] - 0s 2ms/step 

앞서 실습한 로지스틱 회귀 코드와 거의 동일한데 달라진 점은 입력의 차원이 2로 바뀌면서, input_dim의 인자값이 2로 바뀌었다는 점이다. 이는 입력 벡터의 차원이 2임을 의미한다.

정확도는 100%가 나오고 있으므로 800회 정도로 학습을 멈추고 시그모이드 함수의 각 입력값에 대해서 출력값이 0.5보다 크고 작은지를 확인해보겠다.

In [17]:
print(model.predict(X))

[[0.34818274]
 [0.87318677]
 [0.87557006]
 [0.98909533]]


입력값이 둘 다 0, 0인 경우를 제외하고 나머지 3개의 입력 쌍(pair)에 대해서는 전부 값이 0.5를 넘는 것을 볼 수 있다.

### 3.인공 신경망 다이어그램

다중 로지스틱 회귀를 뒤에서 배우게 되는 인공 신경망의 형태로 표현하면 다음과 같다. 아직 인공 신경망을 배우지 않았음에도 이렇게 다이어그램으로 표현해보는 이유는 로지스틱 회귀를 일종의 인공 신경망 구조로 해석해도 무방함을 보여주기 위함이다.

$y = sigmoid(W_1x_1 + W_2x_2 + W_3x_3 + ... + W_nx_n + b) = σ(W_1x_1 + W_2x_2 + W_3x_3 + ... + W_nx_n + b)$

<img src = 'https://wikidocs.net/images/page/35821/multiplelogistic_regression.PNG' width = 60%>
